/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  scott
 * Created: May 21, 2026
 */

create table if not exists Game (
    GameId integer generated by default as identity, 
    EndDtm timestamp(6), StartDtm timestamp default current_timestamp, 
    StsCde char(1), /* hibernate desperately wants to include a check constraint that looks correct but which causes insert to fail. */
    WinnerId integer, 
    primary key (GameId)
);
create table if not exists GamePlayer (GamePlayerId integer generated by default as identity, OrderSeq integer not null, ScoreCnt int default 0, GameId integer not null, PlayerId integer not null, primary key (GamePlayerId));
create table if not exists GamePlayerRound (GamePlayerRoundId integer generated by default as identity, NoteTxt varchar(255), RollingScoreCnt integer, RoundCnt integer not null, RowCreateDtm timestamp default current_timestamp, ScoreCnt integer not null, SvnLtrInd char(1) not null, GamePlayerId integer not null, primary key (GamePlayerRoundId));
create table if not exists Player (PlayerId integer generated by default as identity, NameTxt varchar(255) not null, HighGameId integer, primary key (PlayerId));
